# Generated by Django 5.2.6 on 2025-09-10 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomquote', '0002_user_quote_slug_remove_quote_likes_quote_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='likes',
        ),
        migrations.AlterField(
            model_name='quote',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomquote.source', unique=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='likes',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='randomquote.user'),
        ),
    ]
