# Generated by Django 5.2.6 on 2025-09-10 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomquote', '0003_remove_quote_slug_remove_quote_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomquote.source'),
        ),
    ]
