# Generated by Django 5.2.6 on 2025-09-10 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomquote', '0004_alter_quote_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='likes',
        ),
    ]
