# Generated by Django 5.2.6 on 2025-09-10 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomquote', '0006_remove_quote_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='number_of_quotes',
        ),
        migrations.AddField(
            model_name='quote',
            name='likes',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='randomquote.user'),
        ),
        migrations.AddField(
            model_name='quote',
            name='source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='randomquote.source'),
            preserve_default=False,
        ),
    ]
