# Generated by Django 5.2.6 on 2025-09-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomquote', '0007_remove_source_number_of_quotes_quote_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
