# Generated by Django 5.2.6 on 2025-09-11 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomquote', '0008_alter_source_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='likes',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='randomquote.user'),
        ),
    ]
