# Generated by Django 5.2.6 on 2025-09-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomquote', '0009_alter_quote_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='likes',
        ),
        migrations.AddField(
            model_name='quote',
            name='likes',
            field=models.ManyToManyField(to='randomquote.user'),
        ),
    ]
