# Generated by Django 5.2.6 on 2025-09-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomquote', '0011_delete_user_alter_quote_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
