# Generated by Django 5.2.6 on 2025-09-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomquote', '0013_remove_quote_dislikes_alter_quote_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='weight',
            field=models.IntegerField(default=100),
        ),
    ]
